services:
  torgateway:
    image: alpine:3.24
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: unless-stopped
    networks:
      torgatewaynet:
        ipv4_address: 172.16.50.15
    volumes:
      - ./tor-entrypoint.sh:/bin/tor-entrypoint.sh:ro
      - ./torrc:/etc/tor/torrc:ro
    entrypoint: ["/bin/tor-entrypoint.sh"]
    sysctls:
      net.ipv4.ip_forward: "1"
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
networks:
  torgatewaynet:
    enable_ipv6: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.50.0/24
