services:
  xray:
    image: xray
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 256m
    mem_reservation: 128m
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    read_only: true
    networks:
      xraynet:
        ipv4_address: 177.44.0.66
    restart: unless-stopped
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
      - /run:rw,nosuid,size=4m
    volumes:
      - ./config.json:/usr/local/etc/xray/config.json:ro
    command: ["run", "-config", "/usr/local/etc/xray/config.json"]
    user: "0:0"
    dns:
      - 192.168.1.1
      - 192.168.1.83
      - 192.168.1.88
      - 192.168.1.114
    devices:
      - /dev/net/tun:/dev/net/tun
    privileged: true
networks:
  xraynet:
    enable_ipv6: false
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    ipam:
      config:
        - subnet: 177.44.0.0/24
